create or replace TABLE SAMBA_TV.RAW.ACR (
	SMBA_ID VARCHAR(16777216),
	INTERMEDIATE_ID VARCHAR(16777216),
	EXPOSURE_START_TS NUMBER(38,0),
	EXPOSURE_END_TS NUMBER(38,0),
	DURATION NUMBER(38,0),
	CONTENT_TYPE VARCHAR(16777216),
	CONTENT_ID VARCHAR(16777216),
	TITLE VARCHAR(16777216),
	EPISODE_TITLE VARCHAR(16777216),
	SEASON VARCHAR(16777216),
	EPISODE VARCHAR(16777216),
	DESCRIPTION VARCHAR(16777216),
	GENRES VARCHAR(16777216),
	RELEASE_DATE DATE,
	NETWORK VARCHAR(16777216),
	NETWORK_ID VARCHAR(16777216),
	AFFILIATE_CALL_SIGN VARCHAR(16777216),
	SCHEDULED_PROGRAM_START_TS NUMBER(38,0),
	SCHEDULED_PROGRAM_END_TS NUMBER(38,0),
	CHANNEL_CONTENT_OFFSET_S NUMBER(38,0),
	PROGRAM_CONTENT_OFFSET_S NUMBER(38,0),
	APPLICATION VARCHAR(16777216),
	DMA VARCHAR(16777216),
	ZIP VARCHAR(16777216),
	YYYY NUMBER(4,0),
	MM NUMBER(2,0),
	DD NUMBER(2,0),
	METADATA_DATE DATE
);

create or replace TABLE SAMBA_TV.RAW.GEO_WEIGHTS (
	YYYY VARCHAR(16777216),
	MM VARCHAR(16777216),
	DD VARCHAR(16777216),
	METADATA_DATE DATE,
	HH_ID VARCHAR(16777216),
	SMBA_ID VARCHAR(16777216),
	GEO_WEIGHT FLOAT
);

create or replace TABLE SAMBA_TV.RAW.STB (
	YYYY VARCHAR(16777216) COMMENT 'Four-digit representation of a year.',
	MM VARCHAR(16777216) COMMENT 'The two-digit representation of the month in the date.',
	DD VARCHAR(16777216) COMMENT 'Two-digit codes representing the day of the month.',
	METADATA_DATE DATE COMMENT 'The date when the associated metadata was created or last updated.',
	AFFILIATE_CALL_SIGN VARCHAR(16777216) COMMENT 'Television station call signs.',
	CHANNEL_CONTENT_OFFSET_S NUMBER(38,0) COMMENT 'The offset in seconds for the start of channel content.',
	CONTENT_ID VARCHAR(16777216) COMMENT 'Unique identifier for multimedia content.',
	CONTENT_TYPE VARCHAR(16777216) COMMENT 'The type of content delivered by the set-top box.',
	DESCRIPTION VARCHAR(16777216) COMMENT 'Brief descriptions of various content types found in the STB table''s DESCRIPTION column:\n\n1. Program or content summaries.\n2. Event or show descriptions.\n3. Personality or character introductions.\n4. Abstracts of news articles or reports.\n5. Historical context or background information.\n6. Musical or artistic performance descriptions.\n7. Plot synopses or storylines.\n8. Sports team or athlete descriptions.\n9. Coaching or team background information.\n10. Dialogue or monologue excerpts.',
	DMA VARCHAR(16777216) COMMENT 'Designated Market Area codes.',
	DURATION NUMBER(38,0) COMMENT 'The length of a media program in minutes.',
	EPISODE VARCHAR(16777216) COMMENT 'Unique identifier for a specific television episode.',
	EPISODE_TITLE VARCHAR(16777216) COMMENT 'Titles of television episodes.',
	EXPOSURE_END_TS NUMBER(38,0) COMMENT 'Unix timestamp representing the end time for media exposure.',
	EXPOSURE_START_TS NUMBER(38,0) COMMENT 'Unix timestamp representing the start time of an exposure event.',
	GENRES VARCHAR(16777216) COMMENT 'A column holding data representing various genres of content, encoded as a list of genre codes and their corresponding names.',
	INTERMEDIATE_ID VARCHAR(16777216) COMMENT 'Unique identifier for an intermediate data record.',
	NETWORK VARCHAR(16777216) COMMENT 'The names of television networks.',
	NETWORK_ID VARCHAR(16777216) COMMENT 'Unique identifier for a network or communication system.',
	PROGRAM_CONTENT_OFFSET_S NUMBER(38,0) COMMENT 'The byte offset of a program''s content within a storage block.',
	SCHEDULED_PROGRAM_END_TS NUMBER(38,0) COMMENT 'Unix timestamp representing the scheduled end time of a program in seconds.',
	SCHEDULED_PROGRAM_START_TS NUMBER(38,0) COMMENT 'Unix timestamp representing the scheduled start time of a program.',
	SEASON VARCHAR(16777216) COMMENT 'The season number or label.',
	SMBA_ID VARCHAR(16777216) COMMENT 'Unique identifier for SAMBA\\_TV records.',
	TITLE VARCHAR(16777216) COMMENT 'The title of the television show or video.',
	ZIP VARCHAR(16777216) COMMENT 'Five-digit and sometimes six-digit codes representing specific geographic locations for mail sorting and delivery in the United States.'
);